image: node:10-slim

# from https://gitlab.com/gitlab-org/gitlab-runner/issues/2255
# When using dind, it's wise to use the overlayfs driver for
# improved performance.
variables:
  DOCKER_HOST: tcp://docker:2375

services:
  - docker:dind

cache:
  paths:
    - node_modules/.cache.
    - .yarn-cache

before_script:
  - apt-get update -qq && apt-get install-y iproute2

stages:
  - verify

lint:
  stage: verify
  before_script:
    - yarn config set cache-folder .yarn
    - yarn install --frozen-lockfile --cache-folder .yarn-cache
  script: yarn lint .

test:
  stage: verify
  before_script:
    - yarn config set cache-folder .yarn
    - yarn install --frozen-lockfile --cache-folder .yarn-cache
    - yarn add -W --dev codecov --cache-folder .yarn-cache
  script:
    - yarn jest
      --coverage
  after_script:
    - yarn run codecov --token="${CODECOV_TOKEN}"
  coverage: /All\sfiles.*?\s+(\d+.\d+)/
  artifacts:
    paths:
      - coverage/
    reports:
      junit: coverage/clover.xml
